# Generated by Django 2.2.13 on 2020-12-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Douban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='mid',
        ),
    ]
